[tool.poetry]
name = "oohmatch-diagram"
version = "0.1.0"
description = ""
authors = ["JUNYA MORITA"]

[tool.poetry.dependencies]
python = "^3.8"
diagrams = "^0.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
